### ISSUE TITLE
We need a web server tutorial

### ISSUE THREAD

**Issue by JimBarry** [Esri/geodev-hackerlabs#34]
We need a quick way to:
a. confirm that hacker's machine has a web server installed, configd, and running
b. (if not a) the simplest possible way to get a web server-like thing onto their machine

**Comment by LDittmann** [comment]
a) on the machine running the web server, open a browser and type in http://localhost/   ---- blank page = no functioning web server
b) Apache? interested in hearing others' thoughts -  I have not done this myself
c) is a self-hosted website the best option for this hacker? Would an internal file share or externally hosted site work better with less security risk to the users' home network?

Thanks for posting this question!

**Comment by jgravois** [comment]
@LDittmann thanks for chiming in.  i'd definitely agree that a web server that is only available internally is sufficient.

i plan on writing up instructions for both Python's [SimpleHTTPServer](https://docs.python.org/2/library/simplehttpserver.html) (because Python is included on macs by default and laid down automatically with ArcGIS tools on Windows), and Node's [http-server](https://www.npmjs.com/package/http-server), because they are simple, lightweight, and don't require extensive configuration or admin priviledges on the machine.

**Comment by jgravois** [comment]
i've got a sample [here](https://gist.github.com/jgravois/5e73b56fa7756fd00b89).  
please feel to critique, revise, bash etc.  i've got thick skin and i'm not married to any of it.

cc/ @nixta

**Comment by alaframboise** [comment]
@JimBarry @jgravois  What sections do we need a web server for? WAB?

**Comment by JimBarry** [comment]
WAB doesn't need it, no, but doing stuff with the jsapi or leaflet im assuming does.

**Comment by alaframboise** [comment]
No, if you check out the API exercises in "Develop", they all use jsBin.com. I made sure of it so we wouldn't have this requirement.

e.g https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/develop/add_feature_layers_jsapi.md

Closing.

**Comment by jgravois** [comment]
i know jsbin is convenient, but its garbage for debugging and i think its a poor decision to rely on it in geodev exercises, (particularly since we're using gh-pages to share our own examples).

**Comment by alaframboise** [comment]
@jgravois debugging jsbin is easy. Just select the arrow beside Output and load the page into a stand-alone window, View Source, Click the HTML and boom, it's just like normal debugging in Chrome. Couldn't be easier.

![image](https://cloud.githubusercontent.com/assets/2539681/9910435/f6855bfc-5c51-11e5-8d14-fe60ffb5345e.png)

**Comment by andygup** [comment]
Yup. 

However, to Jim's point it would be easy to list a couple helper links to folks who want to set up IIS on Windows or Apache on Mac. Eventually these folks will have to configure their machine with a local web server.

**Comment by jgravois** [comment]
thats cool, but i didn't know it existed, so i can guarantee that no one getting their feet wet in web development for the first time will either.

what happens when you change a line of code?  close the new window and repeat the process?  if so, thats going to get old after about 3 minutes.

**edit:**
( just realized the two windows are dynamically tied.  which is pretty cool.  i still don't like the fact that you have to sift through the extra code that js.bin injects, but with a tiny tutorial, its an 80% better option than i originally thought)

i understand that it can be tedious to spend time in hackerlabs helping people set up their own environment, but supplying them with documentation in the meetup announcement that mentions both IIS/Apache and lighterweight options like SimpleHTTPServer and spending a few minutes with attendees at the event isn't a waste of time.  it teaches them something that is a fundamental to actually getting real work done.

if anyone has trouble we can still fallback on jsbin if necessary.

**Comment by jgravois** [comment]
decided to just add links to my gist to both the hackerlab meetup announcements and my own exercise.
