### ISSUE TITLE
Consider moving longer labs to it's own sub-category of labs

### ISSUE THREAD

**Issue by alaframboise** [Esri/geodev-hackerlabs#80]
Let's see if we can put the longer, instructor-led labs in a section all on it's own. As we discussed, these labs are a little different than the others and require a lot more coaching.

@jgravois

**Comment by jgravois** [comment]
after our presentation AL and i also settled on a happy medium with regard to providing code snippets....

``` js
query.run(function (evt) {
  // stubbed method call, with direction to write what goes inside
});
```

i'll break out step 1. from my rogue tutorials and make 'setting up your development environment' its own module, then take a stab at improving the instructions a bit so that they don't actually **require** coaching.

**Comment by alaframboise** [comment]
I believe these were moved these as part re-org. Will verify and close when @nixta pushes.

**Comment by nixta** [comment]
@alaframboise & @jgravois: Does the current structure mean we can close this now?

**Comment by jgravois** [comment]
my long labs can still be found in the 'Esri-Leaflet' section of `Develop`.
- GeoEnrich address searches
- Use Geolocation to Query
- Use Geolocation (and turf) to Query

They are _partially_ reworked, but i still haven't gotten around to stubbing out more complete code snippets to make them easier for folks to do on their own.
